version: v2
global:
  runner:
    os_image: ubuntu
tasks:
  deploy:
    type: build
    steps:
      - docker-build:
          image: saurabh3460/restapi01
          push: true

# tasks:
#   build-image:
#     type: build
#     image: saurabh3460/go-api-test
#     push: true
#     tags: ["latest"]
#     dockerfile: Dockerfile
#     context: .
#     runner: golang
