version: v2
global:
  runner:
    os_image: ubuntu
tasks:
  deploy:
    steps:
      - docker-build:
          image: hub.docker.com/repository/docker/saurabh3460/restapi01/general
          push: true
